stages:
  download_smard_prices:
    cmd: python pipeline/01_download_smard_DE_prices.py
    deps:
      - pipeline/01_download_smard_DE_prices.py
      - woe/smard/api.py
      - woe/smard/config.py
      - woe/paths.py
    outs:
      - data/downloads/smard/prices_de_lu.parquet:
          persist: true
  download_residual_load:
    cmd: python pipeline/03_download_residual_load.py
    deps:
      - pipeline/03_download_residual_load.py
      - woe/smard/api.py
      - woe/smard/config.py
      - woe/paths.py
    outs:
      - data/downloads/smard/solar.parquet:
          persist: true
      - data/downloads/smard/wind_onshore.parquet:
          persist: true
      - data/downloads/smard/wind_offshore.parquet:
          persist: true
      - data/downloads/smard/total_load.parquet:
          persist: true
  process_smard_DE_prices:
    cmd: >
      uv run jupytext --to notebook --output book/notebooks/02_smard_DE_prices.ipynb pipeline/02_smard_DE_prices.py &&
      uv run jupyter execute book/notebooks/02_smard_DE_prices.ipynb --inplace
    deps:
      - pipeline/02_smard_DE_prices.py
      - data/downloads/smard/prices_de_lu.parquet
    outs:
      - book/notebooks/02_smard_DE_prices.ipynb:
          cache: false
  