stages:
  download_smard_price_analysis_data:
    cmd: python pipeline/01_download_smard_price_analysis_data.py
    deps:
      - pipeline/01_download_smard_price_analysis_data.py
      - woe/smard/api.py
      - woe/smard/config.py
      - woe/paths.py
    outs:
      - data/downloads/smard/prices_de_lu.parquet:
          persist: true
      - data/downloads/smard/solar.parquet:
          persist: true
      - data/downloads/smard/wind_onshore.parquet:
          persist: true
      - data/downloads/smard/wind_offshore.parquet:
          persist: true
      - data/downloads/smard/total_load.parquet:
          persist: true
      - data/downloads/smard/nuclear.parquet:
          persist: true
      - data/downloads/smard/biomass.parquet:
          persist: true
      - data/downloads/smard/hydro.parquet:
          persist: true
      - data/downloads/smard/capacities.parquet:
          persist: true
  download_ttf_gas:
    cmd: python pipeline/02_download_ttf_gas.py
    deps:
      - pipeline/02_download_ttf_gas.py
      - woe/paths.py
    outs:
      - data/downloads/ttf_gas_prices.parquet:
          persist: true
  download_smard_forecasts:
    cmd: python pipeline/06_download_smard_forecasts.py
    deps:
      - pipeline/06_download_smard_forecasts.py
      - woe/smard/api.py
      - woe/smard/config.py
      - woe/paths.py
    outs:
      - data/downloads/smard/forecast_da_solar.parquet:
          persist: true
      - data/downloads/smard/forecast_da_wind_onshore.parquet:
          persist: true
      - data/downloads/smard/forecast_da_wind_offshore.parquet:
          persist: true
      - data/downloads/smard/forecast_da_load.parquet:
          persist: true
      - data/downloads/smard/forecast_id_solar.parquet:
          persist: true
      - data/downloads/smard/forecast_id_wind_onshore.parquet:
          persist: true
      - data/downloads/smard/forecast_id_wind_offshore.parquet:
          persist: true
  process_smard_DE_prices:
    cmd: >
      MPLBACKEND=Agg python pipeline/03_smard_DE_prices.py &&
      uv run jupytext --to md:myst --output book/notebooks/03_smard_DE_prices.md pipeline/03_smard_DE_prices.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/03_smard_DE_prices.md
    deps:
      - pipeline/03_smard_DE_prices.py
      - woe/paths.py
      - data/downloads/smard/prices_de_lu.parquet
      - data/downloads/smard/solar.parquet
      - data/downloads/smard/wind_onshore.parquet
      - data/downloads/smard/wind_offshore.parquet
      - data/downloads/smard/total_load.parquet
      - data/downloads/ttf_gas_prices.parquet
    outs:
      - book/notebooks/03_smard_DE_prices.md:
          cache: false
      - output/images/03_hourly_prices.png:
          cache: false
      - output/images/03_monthly_avg_prices.png:
          cache: false
      - output/images/03_intraday_3week.png:
          cache: false
      - output/images/03_daily_profile.png:
          cache: false
      - output/images/03_electricity_vs_gas.png:
          cache: false
      - output/images/03_renewables_vs_load.png:
          cache: false
      - output/images/03_monthly_residual_load.png:
          cache: false
      - output/images/03_price_vs_residual_recent.png:
          cache: false
      - output/images/03_price_vs_residual_2025.png:
          cache: false
  process_reconstruct_prices:
    cmd: >
      MPLBACKEND=Agg python pipeline/04_reconstruct_prices.py &&
      uv run jupytext --to md:myst --output book/notebooks/04_reconstruct_prices.md pipeline/04_reconstruct_prices.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/04_reconstruct_prices.md
    deps:
      - pipeline/04_reconstruct_prices.py
      - woe/paths.py
      - data/downloads/smard/prices_de_lu.parquet
      - data/downloads/smard/solar.parquet
      - data/downloads/smard/wind_onshore.parquet
      - data/downloads/smard/wind_offshore.parquet
      - data/downloads/smard/total_load.parquet
      - data/downloads/smard/nuclear.parquet
      - data/downloads/smard/biomass.parquet
      - data/downloads/smard/hydro.parquet
      - data/downloads/smard/capacities.parquet
      - data/downloads/ttf_gas_prices.parquet
      - data/downloads/investing_com/rotterdam_coal_futures.csv
      - data/downloads/investing_com/carbon_emissions_futures.csv
    outs:
      - book/notebooks/04_reconstruct_prices.md:
          cache: false
      - output/images/04_srmc_timeseries.png:
          cache: false
      - output/images/04_monthly_srmc.png:
          cache: false
      - output/images/04_fuel_switching.png:
          cache: false
      - output/images/04_srmc_components.png:
          cache: false
      - output/images/04_actual_vs_reconstructed.png:
          cache: false
      - output/images/04_scatter_reconstructed_vs_actual.png:
          cache: false
      - output/images/04_scatter_residual_load_vs_price.png:
          cache: false
      - output/images/04_scatter_fossil_rl_vs_price.png:
          cache: false
      - output/images/04_r2_comparison.png:
          cache: false
  process_load_seasonalities:
    cmd: >
      MPLBACKEND=Agg python pipeline/05_load_seasonalities.py &&
      uv run jupytext --to md:myst --output book/notebooks/05_load_seasonalities.md pipeline/05_load_seasonalities.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/05_load_seasonalities.md
    deps:
      - pipeline/05_load_seasonalities.py
      - woe/paths.py
      - data/downloads/smard/prices_de_lu.parquet
      - data/downloads/smard/solar.parquet
      - data/downloads/smard/wind_onshore.parquet
      - data/downloads/smard/wind_offshore.parquet
      - data/downloads/smard/total_load.parquet
    outs:
      - book/notebooks/05_load_seasonalities.md:
          cache: false
      - output/images/05_seasonality_solar.png:
          cache: false
      - output/images/05_seasonality_wind.png:
          cache: false
      - output/images/05_seasonality_renewables.png:
          cache: false
      - output/images/05_seasonality_load.png:
          cache: false
      - output/images/05_seasonality_residual_load.png:
          cache: false
      - output/images/05_seasonality_price.png:
          cache: false
  process_ee_seasons:
    cmd: >
      python pipeline/10_ee_seasons.py &&
      uv run jupytext --to md:myst --output book/notebooks/10_ee_seasons.md pipeline/10_ee_seasons.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/10_ee_seasons.md
    deps:
      - pipeline/10_ee_seasons.py
      - woe/paths.py
    outs:
      - book/notebooks/10_ee_seasons.md:
          cache: false
      - output/images/10_ee_temperature_by_hour.gif:
          cache: false
      - output/images/10_ee_temperature_by_month.gif:
          cache: false
      - output/images/10_ee_ndvi_by_doy.gif:
          cache: false
      - output/images/10_ee_ndvi_africa_by_doy.gif:
          cache: false
