stages:
  download_smard_price_analysis_data:
    cmd: python pipeline/01_download_smard_price_analysis_data.py
    deps:
      - pipeline/01_download_smard_price_analysis_data.py
      - woe/smard/api.py
      - woe/smard/config.py
    outs:
      - data/downloads/smard/prices_de_lu.parquet:
          persist: true
      - data/downloads/smard/solar.parquet:
          persist: true
      - data/downloads/smard/wind_onshore.parquet:
          persist: true
      - data/downloads/smard/wind_offshore.parquet:
          persist: true
      - data/downloads/smard/total_load.parquet:
          persist: true
      - data/downloads/smard/nuclear.parquet:
          persist: true
      - data/downloads/smard/biomass.parquet:
          persist: true
      - data/downloads/smard/hydro.parquet:
          persist: true
      - data/downloads/smard/capacities.parquet:
          persist: true
  download_ttf_gas:
    cmd: python pipeline/02_download_ttf_gas.py
    deps:
      - pipeline/02_download_ttf_gas.py
    outs:
      - data/downloads/ttf_gas_prices.parquet:
          persist: true
  download_smard_forecasts:
    cmd: python pipeline/06_download_smard_forecasts.py
    deps:
      - pipeline/06_download_smard_forecasts.py
      - woe/smard/api.py
      - woe/smard/config.py
    outs:
      - data/downloads/smard/forecast_da_solar.parquet:
          persist: true
      - data/downloads/smard/forecast_da_wind_onshore.parquet:
          persist: true
      - data/downloads/smard/forecast_da_wind_offshore.parquet:
          persist: true
      - data/downloads/smard/forecast_da_load.parquet:
          persist: true
      - data/downloads/smard/forecast_id_solar.parquet:
          persist: true
      - data/downloads/smard/forecast_id_wind_onshore.parquet:
          persist: true
      - data/downloads/smard/forecast_id_wind_offshore.parquet:
          persist: true
  process_smard_DE_prices:
    cmd: >
      MPLBACKEND=Agg python pipeline/03_smard_DE_prices.py &&
      uv run jupytext --to md:myst --output book/notebooks/03_smard_DE_prices.md pipeline/03_smard_DE_prices.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/03_smard_DE_prices.md
    deps:
      - pipeline/03_smard_DE_prices.py
      - data/downloads/smard/prices_de_lu.parquet
      - data/downloads/smard/solar.parquet
      - data/downloads/smard/wind_onshore.parquet
      - data/downloads/smard/wind_offshore.parquet
      - data/downloads/smard/total_load.parquet
      - data/downloads/ttf_gas_prices.parquet
    outs:
      - book/notebooks/03_smard_DE_prices.md:
          cache: false
      - output/images/03_hourly_prices.png:
          cache: false
      - output/images/03_monthly_avg_prices.png:
          cache: false
      - output/images/03_intraday_3week.png:
          cache: false
      - output/images/03_daily_profile.png:
          cache: false
      - output/images/03_electricity_vs_gas.png:
          cache: false
      - output/images/03_renewables_vs_load.png:
          cache: false
      - output/images/03_monthly_residual_load.png:
          cache: false
      - output/images/03_price_vs_residual_recent.png:
          cache: false
      - output/images/03_price_vs_residual_2025.png:
          cache: false
  process_reconstruct_prices:
    cmd: >
      MPLBACKEND=Agg python pipeline/04_reconstruct_prices.py &&
      uv run jupytext --to md:myst --output book/notebooks/04_reconstruct_prices.md pipeline/04_reconstruct_prices.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/04_reconstruct_prices.md
    deps:
      - pipeline/04_reconstruct_prices.py
      - data/downloads/smard/prices_de_lu.parquet
      - data/downloads/smard/solar.parquet
      - data/downloads/smard/wind_onshore.parquet
      - data/downloads/smard/wind_offshore.parquet
      - data/downloads/smard/total_load.parquet
      - data/downloads/smard/nuclear.parquet
      - data/downloads/smard/biomass.parquet
      - data/downloads/smard/hydro.parquet
      - data/downloads/smard/capacities.parquet
      - data/downloads/ttf_gas_prices.parquet
      - data/downloads/investing_com/rotterdam_coal_futures.csv
      - data/downloads/investing_com/carbon_emissions_futures.csv
    outs:
      - book/notebooks/04_reconstruct_prices.md:
          cache: false
      - output/images/04_srmc_timeseries.png:
          cache: false
      - output/images/04_monthly_srmc.png:
          cache: false
      - output/images/04_fuel_switching.png:
          cache: false
      - output/images/04_srmc_components.png:
          cache: false
      - output/images/04_actual_vs_reconstructed.png:
          cache: false
      - output/images/04_scatter_reconstructed_vs_actual.png:
          cache: false
      - output/images/04_scatter_residual_load_vs_price.png:
          cache: false
      - output/images/04_scatter_fossil_rl_vs_price.png:
          cache: false
      - output/images/04_r2_comparison.png:
          cache: false
  process_load_seasonalities:
    cmd: >
      MPLBACKEND=Agg python pipeline/05_load_seasonalities.py &&
      uv run jupytext --to md:myst --output book/notebooks/05_load_seasonalities.md pipeline/05_load_seasonalities.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/05_load_seasonalities.md
    deps:
      - pipeline/05_load_seasonalities.py
      - data/downloads/smard/prices_de_lu.parquet
      - data/downloads/smard/solar.parquet
      - data/downloads/smard/wind_onshore.parquet
      - data/downloads/smard/wind_offshore.parquet
      - data/downloads/smard/total_load.parquet
    outs:
      - book/notebooks/05_load_seasonalities.md:
          cache: false
      - output/images/05_seasonality_solar.png:
          cache: false
      - output/images/05_seasonality_wind.png:
          cache: false
      - output/images/05_seasonality_renewables.png:
          cache: false
      - output/images/05_seasonality_load.png:
          cache: false
      - output/images/05_seasonality_residual_load.png:
          cache: false
      - output/images/05_seasonality_price.png:
          cache: false
  process_ee_seasons:
    cmd: >
      python pipeline/10_ee_seasons.py &&
      uv run jupytext --to md:myst --output book/notebooks/10_ee_seasons.md pipeline/10_ee_seasons.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/10_ee_seasons.md
    deps:
      - pipeline/10_ee_seasons.py
    outs:
      - book/notebooks/10_ee_seasons.md:
          cache: false
      - output/images/10_ee_temperature_by_hour.gif:
          cache: false
      - output/images/10_ee_temperature_by_month.gif:
          cache: false
      - output/images/10_ee_ndvi_by_doy.gif:
          cache: false
      - output/images/10_ee_ndvi_africa_by_doy.gif:
          cache: false
  download_era5_single_timestamp:
    cmd: python pipeline/11_download_era5_single_timestamp.py
    deps:
      - pipeline/11_download_era5_single_timestamp.py
    outs:
      - data/downloads/era5/20250603_1200/era5_20250603_1200_surface.nc:
          persist: true
      - data/downloads/era5/20250603_1200/era5_20250603_1200_pressure_levels.nc:
          persist: true
  process_projections:
    cmd: >
      MPLBACKEND=Agg python pipeline/12_projections.py &&
      uv run jupytext --to md:myst --output book/notebooks/12_projections.md pipeline/12_projections.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/12_projections.md
    deps:
      - pipeline/12_projections.py
      - data/downloads/era5/20250603_1200/era5_20250603_1200_surface.nc
    outs:
      - book/notebooks/12_projections.md:
          cache: false
      - output/images/12_t2m_projections_overview.png:
          cache: false
      - output/images/12_t2m_orthographic.png:
          cache: false
      - output/images/12_t2m_robinson.png:
          cache: false
      - output/images/12_t2m_domain.png:
          cache: false
      - output/images/12_t2m_orthographic_nao.png:
          cache: false
  process_pressure_and_weather:
    cmd: >
      MPLBACKEND=Agg python pipeline/13_pressure_and_weather.py &&
      uv run jupytext --to md:myst --output book/notebooks/13_pressure_and_weather.md pipeline/13_pressure_and_weather.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/13_pressure_and_weather.md
    deps:
      - pipeline/13_pressure_and_weather.py
      - data/downloads/era5/20250603_1200/era5_20250603_1200_surface.nc
      - data/downloads/era5/20250603_1200/era5_20250603_1200_pressure_levels.nc
    outs:
      - book/notebooks/13_pressure_and_weather.md:
          cache: false
      - output/images/13_surface_temperature.png:
          cache: false
      - output/images/13_surface_wind.png:
          cache: false
      - output/images/13_cloud_satellite.png:
          cache: false
      - output/images/13_pressure_bands.png:
          cache: false
      - output/images/13_z500_wind250.png:
          cache: false
      - output/images/13_z500_jet_purple.png:
          cache: false
      - output/images/13_t2m_z500.png:
          cache: false
      - output/images/13_t2m_jet_core.png:
          cache: false
      - output/images/13_jet_stream_polar.png:
          cache: false
      - output/images/13_pressure_levels_animation.gif:
          cache: false
      - output/images/13_cross_section_0E.png:
          cache: false
      - output/images/13_cross_section_animation.gif:
          cache: false
      - output/images/13_jet_colmax.png:
          cache: false
  download_monthly_era5:
    cmd: python pipeline/14_download_monthly_era5.py
    deps:
      - pipeline/14_download_monthly_era5.py
    outs:
      - data/downloads/era5/monthly_aggregates/nc/era5_sl_climate.nc:
          persist: true
      - data/downloads/era5/monthly_aggregates/nc/era5_sl_wind_solar.nc:
          persist: true
      - data/downloads/era5/monthly_aggregates/nc/era5_monthly_pressure_levels.nc:
          persist: true
  nc_to_zarr:
    cmd: python pipeline/15_nc_to_zarr.py
    deps:
      - pipeline/15_nc_to_zarr.py
      - data/downloads/era5/monthly_aggregates/nc/era5_sl_climate.nc
      - data/downloads/era5/monthly_aggregates/nc/era5_sl_wind_solar.nc
      - data/downloads/era5/monthly_aggregates/nc/era5_monthly_pressure_levels.nc
    outs:
      - data/downloads/era5/monthly_aggregates/zarr/era5_monthly.zarr:
          persist: true
  compute_germany_time_series:
    cmd: python pipeline/16_compute_germany_time_series.py
    deps:
      - pipeline/16_compute_germany_time_series.py
      - data/downloads/era5/monthly_aggregates/zarr/era5_monthly.zarr
    outs:
      - data/processed/era5/time_series/germany_monthly.parquet
  process_germany_variations:
    cmd: >
      MPLBACKEND=Agg python pipeline/17_germany_variations.py &&
      uv run jupytext --to md:myst --output book/notebooks/17_germany_variations.md pipeline/17_germany_variations.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/17_germany_variations.md
    deps:
      - pipeline/17_germany_variations.py
      - data/processed/era5/time_series/germany_monthly.parquet
      - data/downloads/era5/monthly_aggregates/zarr/era5_monthly.zarr
    outs:
      - book/notebooks/17_germany_variations.md:
          cache: false
      - output/images/17_germany_t2m_jitter.png:
          cache: false
      - output/images/17_germany_wind_jitter.png:
          cache: false
      - output/images/17_germany_ssrd_jitter.png:
          cache: false
      - output/images/17_germany_dunkelflaute.png:
          cache: false
      - output/images/17_january_t2m_comparison.png:
          cache: false
      - output/images/17_january_250hpa_comparison.png:
          cache: false
  process_nao_index:
    cmd: >
      MPLBACKEND=Agg python pipeline/18_nao_index.py &&
      uv run jupytext --to md:myst --output book/notebooks/18_nao_index.md pipeline/18_nao_index.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/18_nao_index.md
    deps:
      - pipeline/18_nao_index.py
      - data/downloads/era5/monthly_aggregates/zarr/era5_monthly.zarr
      - data/processed/era5/time_series/germany_monthly.parquet
    outs:
      - book/notebooks/18_nao_index.md:
          cache: false
      - output/images/15_era5_t2m_2025_01.png:
          cache: false
      - output/images/15_era5_t2m_europe_2025_01.png:
          cache: false
      - output/images/15_era5_t2m_domain_2025_01.png:
          cache: false
      - output/images/15_nao_index.png:
          cache: false
      - output/images/15_nao_t2m_correlation.png:
          cache: false
      - output/images/15_nao_germany_t2m.png:
          cache: false
      - output/images/15_nao_extreme_winters.png:
          cache: false
      - output/images/15_nao_extreme_diff.png:
          cache: false
      - output/images/15_nao_extreme_250hpa_wind.png:
          cache: false
      - output/images/15_nao_extreme_z500.png:
          cache: false
  process_daily_jet_stream_animations:
    cmd: >
      MPLBACKEND=Agg python pipeline/20_daily_jet_stream_animations.py &&
      uv run jupytext --to md:myst --output book/notebooks/20_daily_jet_stream_animations.md pipeline/20_daily_jet_stream_animations.py &&
      sed -i -e 's/```{code-cell}/```{code-cell} python/g' -e '/root_level_metadata_filter/d' book/notebooks/20_daily_jet_stream_animations.md
    deps:
      - pipeline/20_daily_jet_stream_animations.py
      - data/downloads/era5/nao_jetstream/era5_nao_jetstream_2014-2015.nc
      - data/downloads/era5/nao_jetstream/era5_nao_jetstream_2009-2010.nc
    outs:
      - book/notebooks/20_daily_jet_stream_animations.md:
          cache: false
      - output/images/18_t2m_z500_2014-2015.gif:
          cache: false
      - output/images/18_t2m_z500_2009-2010.gif:
          cache: false
      - output/images/18_nao_jet_stream_2014-2015.gif:
          cache: false
      - output/images/18_nao_jet_stream_2009-2010.gif:
          cache: false
      - output/images/18_combined_2014-2015.gif:
          cache: false
      - output/images/18_combined_2009-2010.gif:
          cache: false
  download_daily_nao_jetstream:
    cmd: python pipeline/19_download_daily_nao_jetstream.py
    deps:
      - pipeline/19_download_daily_nao_jetstream.py
    outs:
      - data/downloads/era5/nao_jetstream/era5_nao_jetstream_2014-2015.nc:
          persist: true
      - data/downloads/era5/nao_jetstream/era5_nao_jetstream_2009-2010.nc:
          persist: true
