# ---
# jupytext:
#   text_representation:
#     format_name: percent
# kernelspec:
#   display_name: Python 3
#   language: python
#   name: python3
# ---

# %% [markdown]
# # NAO and Jet Stream — Daily Evolution
#
# The **North Atlantic Oscillation (NAO)** is the leading mode of atmospheric
# variability over the North Atlantic.  Its sign determines whether the
# mid-latitude jet stream is amplified and tracking north-east into Europe
# (NAO+) or weakened and shifted south, with Rossby-wave ridges blocking the
# westerly flow (NAO−).
#
# This chapter animates two contrasting DJF (December–February) winters:
#
# | Period | NAO phase | Character |
# |--------|-----------|-----------|
# | 2014–2015 | Strong NAO+ | Mild, stormy, vigorous westerlies over Europe |
# | 2009–2010 | Strong NAO− | Cold, blocked, persistent high-pressure over Europe |
#
# Each animation frame shows:
# - **Z500 geopotential height** (500 hPa) as labelled contour lines — ridges
#   (high Z500) and troughs (low Z500) reveal the large-scale wave pattern.
# - **Jet stream** (250 hPa wind speed ≥ 30 m/s) filled in purple — the
#   core of the upper-tropospheric westerly flow.
#
# Data source: ERA5 reanalysis downloaded from ARCO-ERA5 (Google Cloud),
# daily at 12:00 UTC.
#
# Animations are generated by `pipeline/20_generate_jet_stream_animations.py`.

# %% [markdown]
# ## 2m temperature and Z500 — surface air mass perspective
#
# The first set of animations shows **2m temperature** as a filled colour field
# with **500 hPa geopotential height (Z500)** as labelled contour lines on top.
# This combination is the classic synoptic-meteorology view of the lower
# troposphere: the temperature field reveals where cold polar air has invaded
# and where warm maritime air is advected, while the Z500 contours show the
# steering-level ridge/trough pattern that drives that advection.

# %% [markdown]
# #### NAO+ winter 2014–2015 — temperature and Z500
#
# ```{figure} ../../output/images/18_t2m_z500_2014-2015.gif
# :name: fig-18-t2m-z500-2014-2015
# Daily 2m temperature (colour, °C) and 500 hPa geopotential height (contour
# lines, m) during the NAO+ winter of December 2014 – February 2015.  The
# tightly packed Z500 contours over the North Atlantic reflect the strong
# westerly pressure gradient; mild maritime air (red/orange) is advected
# persistently into western and central Europe.  ERA5 reanalysis, 12:00 UTC.
# ```

# %% [markdown]
# #### NAO− winter 2009–2010 — temperature and Z500
#
# ```{figure} ../../output/images/18_t2m_z500_2009-2010.gif
# :name: fig-18-t2m-z500-2009-2010
# Daily 2m temperature (colour, °C) and 500 hPa geopotential height (contour
# lines, m) during the NAO− winter of December 2009 – February 2010.  A
# persistent Z500 ridge over Greenland and Scandinavia (widely spaced, elevated
# contours) channels cold Arctic air (blue) southward over the European
# continent.  ERA5 reanalysis, 12:00 UTC.
# ```

# %% [markdown]
# ## Jet stream — upper-tropospheric flow
#
# The second set of animations focuses on the **jet stream** at 250 hPa,
# the level where upper-tropospheric winds are strongest.  The jet stream
# position and strength are tightly coupled to the Z500 pattern above: in NAO+
# winters it flows vigorously north-eastward across the Atlantic; in NAO−
# winters it weakens or splits, allowing persistent blocking.

# %% [markdown]
# ## NAO+ winter: 2014–2015
#
# The 2014–2015 winter was dominated by a strongly positive NAO.  Persistent
# westerly flow channelled a procession of Atlantic depressions into western
# and central Europe, bringing above-average temperatures and above-average
# storm activity.  The animation shows a tight, zonally oriented jet stream
# tracking north-eastward across the Atlantic into the British Isles and
# Scandinavia, with Z500 contours packed closely together — indicating a
# strong meridional pressure gradient.
#
# ```{figure} ../../output/images/18_nao_jet_stream_2014-2015.gif
# :name: fig-18-nao-jet-2014-2015
# Daily evolution of Z500 geopotential height (contour lines, m) and the
# 250 hPa jet stream core (purple, ≥ 30 m/s) during the NAO+ winter of
# December 2014 – February 2015.  ERA5 reanalysis, 12:00 UTC each day.
# ```

# %% [markdown]
# ## NAO− winter: 2009–2010
#
# The 2009–2010 winter was one of the strongest NAO− episodes in recent
# decades.  A persistent blocking anticyclone over Greenland and Scandinavia
# deflected the jet stream southward, cutting off the supply of mild maritime
# air to central Europe.  Much of the continent experienced a prolonged cold
# spell with temperatures several degrees below the seasonal norm.  The
# animation shows a split or southward-displaced jet, with high Z500 ridges
# anchored over northern Europe — the hallmark of an atmospheric blocking
# pattern.
#
# ```{figure} ../../output/images/18_nao_jet_stream_2009-2010.gif
# :name: fig-18-nao-jet-2009-2010
# Daily evolution of Z500 geopotential height (contour lines, m) and the
# 250 hPa jet stream core (purple, ≥ 30 m/s) during the NAO− winter of
# December 2009 – February 2010.  ERA5 reanalysis, 12:00 UTC each day.
# ```

# %% [markdown]
# ## Combined view — jet stream and temperature side by side
#
# The combined animation places both perspectives in a single frame:
# the **left panel** shows Z500 contours with the jet stream (purple) and
# the **right panel** shows the same Z500 contours over 2m temperature.
# Seeing them together makes it easier to trace how the upper-level wave
# pattern simultaneously positions the jet and controls cold/warm air advection
# at the surface.

# %% [markdown]
# ### NAO+ winter 2014–2015 — combined view
#
# ```{figure} ../../output/images/18_combined_2014-2015.gif
# :name: fig-18-combined-2014-2015
# Side-by-side daily animation for the NAO+ winter of December 2014 –
# February 2015.  Left: Z500 geopotential height (contour lines, m) with the
# 250 hPa jet stream core (purple, ≥ 30 m/s).  Right: same Z500 contours
# over 2m temperature (°C).  ERA5 reanalysis, 12:00 UTC each day.
# ```

# %% [markdown]
# ### NAO− winter 2009–2010 — combined view
#
# ```{figure} ../../output/images/18_combined_2009-2010.gif
# :name: fig-18-combined-2009-2010
# Side-by-side daily animation for the NAO− winter of December 2009 –
# February 2010.  Left: Z500 geopotential height (contour lines, m) with the
# 250 hPa jet stream core (purple, ≥ 30 m/s).  Right: same Z500 contours
# over 2m temperature (°C).  ERA5 reanalysis, 12:00 UTC each day.
# ```
